# Generated by Django 4.2.2 on 2023-06-19 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=400)),
                ('imageUrl', models.URLField(default='/static/images/register_background.jpg', max_length=400, null=True)),
                ('publishedDate', models.DateTimeField(default=datetime.datetime(2023, 6, 19, 9, 19, 36, 823567, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(default=datetime.datetime(2023, 6, 19, 9, 19, 36, 823824, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
