# Generated by Django 4.2.2 on 2023-06-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_featurednews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurednews',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='featurednews',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
