# Generated by Django 4.2.2 on 2023-06-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_featurednews_slug_alter_featurednews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurednews',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='featurednews',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
