# Generated by Django 4.2.2 on 2023-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_communitynews_alter_featurednews_slug_upvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynews',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('lifestyle', 'Lifestyle'), ('technology', 'Technology'), ('others', 'Others')], default='lifestyle', max_length=20),
        ),
    ]
