# Generated by Django 4.2.2 on 2023-06-20 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_communitynews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
