# Generated by Django 4.2.2 on 2023-06-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_comment_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynews',
            name='banner',
            field=models.ImageField(default='/static/images/default_news.jpg', upload_to='community_news'),
        ),
    ]
