# Generated by Django 4.2.2 on 2023-06-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_communitynews_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynews',
            name='banner',
            field=models.ImageField(default='default_news.jpg', upload_to='community_news'),
        ),
    ]
